### ISSUE TITLE
navbar tabs on focus are green color

### ISSUE THREAD

**Issue by biswajit-k** [biswajit-k/MonoSlate#1]
The nav bar tabs(_blog, project, about, resume_) get a green border when they get focused while navigating site through the tab key. 

See the image below-
<img width="305" alt="navbar_tab_navigation" src="https://github.com/user-attachments/assets/224664d1-2ed1-4b50-8582-1f2602ef1710">

Changing the tab color to some gray shade is expected.

**Comment by biswajit-k** [comment]
For reference, some styles are present in `GlobalStyle.js` that manage the color to be shown on focus. The gray shades are present in `variables.js` file.

**Comment by SalmanDeveloperz** [comment]
Hi @biswajit-k ,
I’d like to work on this issue. Could you please assign it to me?

Thank you!
Muhammad Salman

**Comment by SalmanDeveloperz** [comment]
Hi @biswajit-k,

I wanted to let you know that I’ve addressed the issue regarding the tab color. For the focus state of the navbar tabs, I’ve applied the --medium-gray (#495057) color, which I believe provides a balanced contrast while keeping the green border as described.

Here’s the [Pull Request](https://github.com/biswajit-k/MonoSlate/pull/5) with the changes. Please review and let me know if any further adjustments are needed.

Thank you!

Muhammad Salman
