### ISSUE TITLE
Enhance Mobile Responsiveness of Projects Page

### ISSUE THREAD

**Issue by s-babaeizadeh** [biswajit-k/MonoSlate#2]
The Projects page requires enhancements to ensure it is fully responsive on mobile devices. Currently, the layout and elements do not adapt well to smaller screens, leading to a suboptimal user experience.

**Comment by biswajit-k** [comment]
Hi @s-babaeizadeh, I have checked the responsiveness of project page and it works smooth. Please look at the recording below for reference. Please let me know if there is something specific that you are talking about.


https://github.com/user-attachments/assets/0c4abf72-644d-44c0-bd44-0023180f1fc9

**Comment by biswajit-k** [comment]
Please feel free to re-open if there is something specific that we can address.
