### ISSUE TITLE
Twitter logo change

### ISSUE THREAD

**Issue by SiddhanthKapoor** [biswajit-k/MonoSlate#6]
The Twitter logo that appears on your website is still the old bird logo where as the logo has been changed to an x .
I would like to get this issue assigned and would love to hear back from you !

**Comment by shreyajaiswal17** [comment]
@SiddhanthKapoor I would like to work on this kindly assign this to me under Hactoberfest.

**Comment by biswajit-k** [comment]
Sorry for the late reply, I got caught up with some work. Assigning it to @SiddhanthKapoor for now.
